spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/ceos18-tutorial
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

logging:
  level:
    org.hibernate.SQL: debug